num3 = int(input("enter first a number?: "))
num4 = int(input("enter second a number?: "))
print(str(num3) + "17")
print(float(num3) + 4.2)
print((num4) + num3)
print(num4 // 15)
print(num4 / 7.8)
print(num4 % num3)
print(num3 > num4)
print(num3 < num4)
print(num3 == num4)